### ISSUE TITLE
NUTS Adaptive Metric

### ISSUE THREAD

**Issue by JamesYang007** [JamesYang007/autoppl#29]
- [x] Refactor NUTS
- [x] Adaptive stuff should be abstracted out
- [x] Implement Welford's algorithm
- [x] Implement Hamiltonian for diagonal metric
- [x] Allow users to set options for adaptiveness?
- [x] Make configuration struct to pass into NUTS

**Comment by JamesYang007** [comment]
#30

**Comment by jacobaustin123** [comment]
closed by 481ce719cf99.
